export interface Company {
	CompanyId: string,
	CompanyName: string,
	TVA: string,
	Shareholders: string,
	CIF: string,
	COM: string,
	Headquarter: string,
	Subsidiary: string,
	MainActivity: string,
	SecondaryActivity: string,
	Interests: string,
	Email: string,
	Region: string,
	Employees: string,
	StatusEmail: string,
	DataYear: string,
	Profit: string,
	Loss: string,
	Turnover: string,
	Capital: string,
	Liabilities: string,
	Assets: string,
	IsActive: string
};

export const getEmptyCompany = (): Company => ({
	CompanyId: "",
	CompanyName: "",
	TVA: "",
	Shareholders: "",
	CIF: "",
	COM: "",
	Headquarter: "",
	Subsidiary: "",
	MainActivity: "",
	SecondaryActivity: "",
	Interests: "",
	Email: "",
	Region: "",
	Employees: "",
	StatusEmail: "",
	DataYear: "",
	Profit: "",
	Loss: "",
	Turnover: "",
	Capital: "",
	Liabilities: "",
	Assets: "",
	IsActive: ""
});